/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterProfileRouteImport } from './routes/register-profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitizenIndexRouteImport } from './routes/citizen/index'
import { Route as CitizenApplicationsRouteImport } from './routes/citizen/applications'
import { Route as AdminSystemRouteRouteImport } from './routes/admin/system/route'
import { Route as AdminKabaleRouteRouteImport } from './routes/admin/kabale/route'
import { Route as AdminSystemIndexRouteImport } from './routes/admin/system/index'
import { Route as AdminKabaleIndexRouteImport } from './routes/admin/kabale/index'
import { Route as AdminKabaleDigitalIdsRouteImport } from './routes/admin/kabale/digital-ids'
import { Route as AdminKabaleApplicationsRouteImport } from './routes/admin/kabale/applications'
import { Route as AdminSystemUsersIndexRouteImport } from './routes/admin/system/users/index'
import { Route as AdminSystemKabalesIndexRouteImport } from './routes/admin/system/kabales/index'
import { Route as AdminSystemDigitalIdsIndexRouteImport } from './routes/admin/system/digital-ids/index'
import { Route as AdminSystemCitizensIndexRouteImport } from './routes/admin/system/citizens/index'
import { Route as AdminSystemApplicationsIndexRouteImport } from './routes/admin/system/applications/index'
import { Route as AdminSystemUsersCreateRouteImport } from './routes/admin/system/users/create'
import { Route as AdminSystemUsersUserIdRouteImport } from './routes/admin/system/users/$userId_'
import { Route as AdminSystemKabalesCreateRouteImport } from './routes/admin/system/kabales/create'
import { Route as AdminSystemKabalesKabaleIdRouteImport } from './routes/admin/system/kabales/$kabaleId_'
import { Route as AdminSystemCitizensCitizenIdRouteImport } from './routes/admin/system/citizens/$citizenId'
import { Route as AdminSystemUsersUserIdEditRouteImport } from './routes/admin/system/users/$userId.edit'
import { Route as AdminSystemKabalesKabaleIdEditRouteImport } from './routes/admin/system/kabales/$kabaleId.edit'

const RegisterProfileRoute = RegisterProfileRouteImport.update({
  id: '/register-profile',
  path: '/register-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/citizen/',
  path: '/citizen/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenApplicationsRoute = CitizenApplicationsRouteImport.update({
  id: '/citizen/applications',
  path: '/citizen/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRouteRoute = AdminSystemRouteRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKabaleRouteRoute = AdminKabaleRouteRouteImport.update({
  id: '/admin/kabale',
  path: '/admin/kabale',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemIndexRoute = AdminSystemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSystemRouteRoute,
} as any)
const AdminKabaleIndexRoute = AdminKabaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminKabaleRouteRoute,
} as any)
const AdminKabaleDigitalIdsRoute = AdminKabaleDigitalIdsRouteImport.update({
  id: '/digital-ids',
  path: '/digital-ids',
  getParentRoute: () => AdminKabaleRouteRoute,
} as any)
const AdminKabaleApplicationsRoute = AdminKabaleApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminKabaleRouteRoute,
} as any)
const AdminSystemUsersIndexRoute = AdminSystemUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminSystemRouteRoute,
} as any)
const AdminSystemKabalesIndexRoute = AdminSystemKabalesIndexRouteImport.update({
  id: '/kabales/',
  path: '/kabales/',
  getParentRoute: () => AdminSystemRouteRoute,
} as any)
const AdminSystemDigitalIdsIndexRoute =
  AdminSystemDigitalIdsIndexRouteImport.update({
    id: '/digital-ids/',
    path: '/digital-ids/',
    getParentRoute: () => AdminSystemRouteRoute,
  } as any)
const AdminSystemCitizensIndexRoute =
  AdminSystemCitizensIndexRouteImport.update({
    id: '/citizens/',
    path: '/citizens/',
    getParentRoute: () => AdminSystemRouteRoute,
  } as any)
const AdminSystemApplicationsIndexRoute =
  AdminSystemApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AdminSystemRouteRoute,
  } as any)
const AdminSystemUsersCreateRoute = AdminSystemUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AdminSystemRouteRoute,
} as any)
const AdminSystemUsersUserIdRoute = AdminSystemUsersUserIdRouteImport.update({
  id: '/users/$userId_',
  path: '/users/$userId',
  getParentRoute: () => AdminSystemRouteRoute,
} as any)
const AdminSystemKabalesCreateRoute =
  AdminSystemKabalesCreateRouteImport.update({
    id: '/kabales/create',
    path: '/kabales/create',
    getParentRoute: () => AdminSystemRouteRoute,
  } as any)
const AdminSystemKabalesKabaleIdRoute =
  AdminSystemKabalesKabaleIdRouteImport.update({
    id: '/kabales/$kabaleId_',
    path: '/kabales/$kabaleId',
    getParentRoute: () => AdminSystemRouteRoute,
  } as any)
const AdminSystemCitizensCitizenIdRoute =
  AdminSystemCitizensCitizenIdRouteImport.update({
    id: '/citizens/$citizenId',
    path: '/citizens/$citizenId',
    getParentRoute: () => AdminSystemRouteRoute,
  } as any)
const AdminSystemUsersUserIdEditRoute =
  AdminSystemUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AdminSystemRouteRoute,
  } as any)
const AdminSystemKabalesKabaleIdEditRoute =
  AdminSystemKabalesKabaleIdEditRouteImport.update({
    id: '/kabales/$kabaleId/edit',
    path: '/kabales/$kabaleId/edit',
    getParentRoute: () => AdminSystemRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/register-profile': typeof RegisterProfileRoute
  '/admin/kabale': typeof AdminKabaleRouteRouteWithChildren
  '/admin/system': typeof AdminSystemRouteRouteWithChildren
  '/citizen/applications': typeof CitizenApplicationsRoute
  '/citizen': typeof CitizenIndexRoute
  '/admin/kabale/applications': typeof AdminKabaleApplicationsRoute
  '/admin/kabale/digital-ids': typeof AdminKabaleDigitalIdsRoute
  '/admin/kabale/': typeof AdminKabaleIndexRoute
  '/admin/system/': typeof AdminSystemIndexRoute
  '/admin/system/citizens/$citizenId': typeof AdminSystemCitizensCitizenIdRoute
  '/admin/system/kabales/$kabaleId': typeof AdminSystemKabalesKabaleIdRoute
  '/admin/system/kabales/create': typeof AdminSystemKabalesCreateRoute
  '/admin/system/users/$userId': typeof AdminSystemUsersUserIdRoute
  '/admin/system/users/create': typeof AdminSystemUsersCreateRoute
  '/admin/system/applications': typeof AdminSystemApplicationsIndexRoute
  '/admin/system/citizens': typeof AdminSystemCitizensIndexRoute
  '/admin/system/digital-ids': typeof AdminSystemDigitalIdsIndexRoute
  '/admin/system/kabales': typeof AdminSystemKabalesIndexRoute
  '/admin/system/users': typeof AdminSystemUsersIndexRoute
  '/admin/system/kabales/$kabaleId/edit': typeof AdminSystemKabalesKabaleIdEditRoute
  '/admin/system/users/$userId/edit': typeof AdminSystemUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/register-profile': typeof RegisterProfileRoute
  '/citizen/applications': typeof CitizenApplicationsRoute
  '/citizen': typeof CitizenIndexRoute
  '/admin/kabale/applications': typeof AdminKabaleApplicationsRoute
  '/admin/kabale/digital-ids': typeof AdminKabaleDigitalIdsRoute
  '/admin/kabale': typeof AdminKabaleIndexRoute
  '/admin/system': typeof AdminSystemIndexRoute
  '/admin/system/citizens/$citizenId': typeof AdminSystemCitizensCitizenIdRoute
  '/admin/system/kabales/$kabaleId': typeof AdminSystemKabalesKabaleIdRoute
  '/admin/system/kabales/create': typeof AdminSystemKabalesCreateRoute
  '/admin/system/users/$userId': typeof AdminSystemUsersUserIdRoute
  '/admin/system/users/create': typeof AdminSystemUsersCreateRoute
  '/admin/system/applications': typeof AdminSystemApplicationsIndexRoute
  '/admin/system/citizens': typeof AdminSystemCitizensIndexRoute
  '/admin/system/digital-ids': typeof AdminSystemDigitalIdsIndexRoute
  '/admin/system/kabales': typeof AdminSystemKabalesIndexRoute
  '/admin/system/users': typeof AdminSystemUsersIndexRoute
  '/admin/system/kabales/$kabaleId/edit': typeof AdminSystemKabalesKabaleIdEditRoute
  '/admin/system/users/$userId/edit': typeof AdminSystemUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/register-profile': typeof RegisterProfileRoute
  '/admin/kabale': typeof AdminKabaleRouteRouteWithChildren
  '/admin/system': typeof AdminSystemRouteRouteWithChildren
  '/citizen/applications': typeof CitizenApplicationsRoute
  '/citizen/': typeof CitizenIndexRoute
  '/admin/kabale/applications': typeof AdminKabaleApplicationsRoute
  '/admin/kabale/digital-ids': typeof AdminKabaleDigitalIdsRoute
  '/admin/kabale/': typeof AdminKabaleIndexRoute
  '/admin/system/': typeof AdminSystemIndexRoute
  '/admin/system/citizens/$citizenId': typeof AdminSystemCitizensCitizenIdRoute
  '/admin/system/kabales/$kabaleId_': typeof AdminSystemKabalesKabaleIdRoute
  '/admin/system/kabales/create': typeof AdminSystemKabalesCreateRoute
  '/admin/system/users/$userId_': typeof AdminSystemUsersUserIdRoute
  '/admin/system/users/create': typeof AdminSystemUsersCreateRoute
  '/admin/system/applications/': typeof AdminSystemApplicationsIndexRoute
  '/admin/system/citizens/': typeof AdminSystemCitizensIndexRoute
  '/admin/system/digital-ids/': typeof AdminSystemDigitalIdsIndexRoute
  '/admin/system/kabales/': typeof AdminSystemKabalesIndexRoute
  '/admin/system/users/': typeof AdminSystemUsersIndexRoute
  '/admin/system/kabales/$kabaleId/edit': typeof AdminSystemKabalesKabaleIdEditRoute
  '/admin/system/users/$userId/edit': typeof AdminSystemUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/profile'
    | '/register'
    | '/register-profile'
    | '/admin/kabale'
    | '/admin/system'
    | '/citizen/applications'
    | '/citizen'
    | '/admin/kabale/applications'
    | '/admin/kabale/digital-ids'
    | '/admin/kabale/'
    | '/admin/system/'
    | '/admin/system/citizens/$citizenId'
    | '/admin/system/kabales/$kabaleId'
    | '/admin/system/kabales/create'
    | '/admin/system/users/$userId'
    | '/admin/system/users/create'
    | '/admin/system/applications'
    | '/admin/system/citizens'
    | '/admin/system/digital-ids'
    | '/admin/system/kabales'
    | '/admin/system/users'
    | '/admin/system/kabales/$kabaleId/edit'
    | '/admin/system/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/profile'
    | '/register'
    | '/register-profile'
    | '/citizen/applications'
    | '/citizen'
    | '/admin/kabale/applications'
    | '/admin/kabale/digital-ids'
    | '/admin/kabale'
    | '/admin/system'
    | '/admin/system/citizens/$citizenId'
    | '/admin/system/kabales/$kabaleId'
    | '/admin/system/kabales/create'
    | '/admin/system/users/$userId'
    | '/admin/system/users/create'
    | '/admin/system/applications'
    | '/admin/system/citizens'
    | '/admin/system/digital-ids'
    | '/admin/system/kabales'
    | '/admin/system/users'
    | '/admin/system/kabales/$kabaleId/edit'
    | '/admin/system/users/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/forbidden'
    | '/login'
    | '/profile'
    | '/register'
    | '/register-profile'
    | '/admin/kabale'
    | '/admin/system'
    | '/citizen/applications'
    | '/citizen/'
    | '/admin/kabale/applications'
    | '/admin/kabale/digital-ids'
    | '/admin/kabale/'
    | '/admin/system/'
    | '/admin/system/citizens/$citizenId'
    | '/admin/system/kabales/$kabaleId_'
    | '/admin/system/kabales/create'
    | '/admin/system/users/$userId_'
    | '/admin/system/users/create'
    | '/admin/system/applications/'
    | '/admin/system/citizens/'
    | '/admin/system/digital-ids/'
    | '/admin/system/kabales/'
    | '/admin/system/users/'
    | '/admin/system/kabales/$kabaleId/edit'
    | '/admin/system/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RegisterProfileRoute: typeof RegisterProfileRoute
  AdminKabaleRouteRoute: typeof AdminKabaleRouteRouteWithChildren
  AdminSystemRouteRoute: typeof AdminSystemRouteRouteWithChildren
  CitizenApplicationsRoute: typeof CitizenApplicationsRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-profile': {
      id: '/register-profile'
      path: '/register-profile'
      fullPath: '/register-profile'
      preLoaderRoute: typeof RegisterProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/applications': {
      id: '/citizen/applications'
      path: '/citizen/applications'
      fullPath: '/citizen/applications'
      preLoaderRoute: typeof CitizenApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kabale': {
      id: '/admin/kabale'
      path: '/admin/kabale'
      fullPath: '/admin/kabale'
      preLoaderRoute: typeof AdminKabaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system/': {
      id: '/admin/system/'
      path: '/'
      fullPath: '/admin/system/'
      preLoaderRoute: typeof AdminSystemIndexRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/kabale/': {
      id: '/admin/kabale/'
      path: '/'
      fullPath: '/admin/kabale/'
      preLoaderRoute: typeof AdminKabaleIndexRouteImport
      parentRoute: typeof AdminKabaleRouteRoute
    }
    '/admin/kabale/digital-ids': {
      id: '/admin/kabale/digital-ids'
      path: '/digital-ids'
      fullPath: '/admin/kabale/digital-ids'
      preLoaderRoute: typeof AdminKabaleDigitalIdsRouteImport
      parentRoute: typeof AdminKabaleRouteRoute
    }
    '/admin/kabale/applications': {
      id: '/admin/kabale/applications'
      path: '/applications'
      fullPath: '/admin/kabale/applications'
      preLoaderRoute: typeof AdminKabaleApplicationsRouteImport
      parentRoute: typeof AdminKabaleRouteRoute
    }
    '/admin/system/users/': {
      id: '/admin/system/users/'
      path: '/users'
      fullPath: '/admin/system/users'
      preLoaderRoute: typeof AdminSystemUsersIndexRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/system/kabales/': {
      id: '/admin/system/kabales/'
      path: '/kabales'
      fullPath: '/admin/system/kabales'
      preLoaderRoute: typeof AdminSystemKabalesIndexRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/system/digital-ids/': {
      id: '/admin/system/digital-ids/'
      path: '/digital-ids'
      fullPath: '/admin/system/digital-ids'
      preLoaderRoute: typeof AdminSystemDigitalIdsIndexRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/system/citizens/': {
      id: '/admin/system/citizens/'
      path: '/citizens'
      fullPath: '/admin/system/citizens'
      preLoaderRoute: typeof AdminSystemCitizensIndexRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/system/applications/': {
      id: '/admin/system/applications/'
      path: '/applications'
      fullPath: '/admin/system/applications'
      preLoaderRoute: typeof AdminSystemApplicationsIndexRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/system/users/create': {
      id: '/admin/system/users/create'
      path: '/users/create'
      fullPath: '/admin/system/users/create'
      preLoaderRoute: typeof AdminSystemUsersCreateRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/system/users/$userId_': {
      id: '/admin/system/users/$userId_'
      path: '/users/$userId'
      fullPath: '/admin/system/users/$userId'
      preLoaderRoute: typeof AdminSystemUsersUserIdRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/system/kabales/create': {
      id: '/admin/system/kabales/create'
      path: '/kabales/create'
      fullPath: '/admin/system/kabales/create'
      preLoaderRoute: typeof AdminSystemKabalesCreateRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/system/kabales/$kabaleId_': {
      id: '/admin/system/kabales/$kabaleId_'
      path: '/kabales/$kabaleId'
      fullPath: '/admin/system/kabales/$kabaleId'
      preLoaderRoute: typeof AdminSystemKabalesKabaleIdRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/system/citizens/$citizenId': {
      id: '/admin/system/citizens/$citizenId'
      path: '/citizens/$citizenId'
      fullPath: '/admin/system/citizens/$citizenId'
      preLoaderRoute: typeof AdminSystemCitizensCitizenIdRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/system/users/$userId/edit': {
      id: '/admin/system/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/admin/system/users/$userId/edit'
      preLoaderRoute: typeof AdminSystemUsersUserIdEditRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
    '/admin/system/kabales/$kabaleId/edit': {
      id: '/admin/system/kabales/$kabaleId/edit'
      path: '/kabales/$kabaleId/edit'
      fullPath: '/admin/system/kabales/$kabaleId/edit'
      preLoaderRoute: typeof AdminSystemKabalesKabaleIdEditRouteImport
      parentRoute: typeof AdminSystemRouteRoute
    }
  }
}

interface AdminKabaleRouteRouteChildren {
  AdminKabaleApplicationsRoute: typeof AdminKabaleApplicationsRoute
  AdminKabaleDigitalIdsRoute: typeof AdminKabaleDigitalIdsRoute
  AdminKabaleIndexRoute: typeof AdminKabaleIndexRoute
}

const AdminKabaleRouteRouteChildren: AdminKabaleRouteRouteChildren = {
  AdminKabaleApplicationsRoute: AdminKabaleApplicationsRoute,
  AdminKabaleDigitalIdsRoute: AdminKabaleDigitalIdsRoute,
  AdminKabaleIndexRoute: AdminKabaleIndexRoute,
}

const AdminKabaleRouteRouteWithChildren =
  AdminKabaleRouteRoute._addFileChildren(AdminKabaleRouteRouteChildren)

interface AdminSystemRouteRouteChildren {
  AdminSystemIndexRoute: typeof AdminSystemIndexRoute
  AdminSystemCitizensCitizenIdRoute: typeof AdminSystemCitizensCitizenIdRoute
  AdminSystemKabalesKabaleIdRoute: typeof AdminSystemKabalesKabaleIdRoute
  AdminSystemKabalesCreateRoute: typeof AdminSystemKabalesCreateRoute
  AdminSystemUsersUserIdRoute: typeof AdminSystemUsersUserIdRoute
  AdminSystemUsersCreateRoute: typeof AdminSystemUsersCreateRoute
  AdminSystemApplicationsIndexRoute: typeof AdminSystemApplicationsIndexRoute
  AdminSystemCitizensIndexRoute: typeof AdminSystemCitizensIndexRoute
  AdminSystemDigitalIdsIndexRoute: typeof AdminSystemDigitalIdsIndexRoute
  AdminSystemKabalesIndexRoute: typeof AdminSystemKabalesIndexRoute
  AdminSystemUsersIndexRoute: typeof AdminSystemUsersIndexRoute
  AdminSystemKabalesKabaleIdEditRoute: typeof AdminSystemKabalesKabaleIdEditRoute
  AdminSystemUsersUserIdEditRoute: typeof AdminSystemUsersUserIdEditRoute
}

const AdminSystemRouteRouteChildren: AdminSystemRouteRouteChildren = {
  AdminSystemIndexRoute: AdminSystemIndexRoute,
  AdminSystemCitizensCitizenIdRoute: AdminSystemCitizensCitizenIdRoute,
  AdminSystemKabalesKabaleIdRoute: AdminSystemKabalesKabaleIdRoute,
  AdminSystemKabalesCreateRoute: AdminSystemKabalesCreateRoute,
  AdminSystemUsersUserIdRoute: AdminSystemUsersUserIdRoute,
  AdminSystemUsersCreateRoute: AdminSystemUsersCreateRoute,
  AdminSystemApplicationsIndexRoute: AdminSystemApplicationsIndexRoute,
  AdminSystemCitizensIndexRoute: AdminSystemCitizensIndexRoute,
  AdminSystemDigitalIdsIndexRoute: AdminSystemDigitalIdsIndexRoute,
  AdminSystemKabalesIndexRoute: AdminSystemKabalesIndexRoute,
  AdminSystemUsersIndexRoute: AdminSystemUsersIndexRoute,
  AdminSystemKabalesKabaleIdEditRoute: AdminSystemKabalesKabaleIdEditRoute,
  AdminSystemUsersUserIdEditRoute: AdminSystemUsersUserIdEditRoute,
}

const AdminSystemRouteRouteWithChildren =
  AdminSystemRouteRoute._addFileChildren(AdminSystemRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RegisterProfileRoute: RegisterProfileRoute,
  AdminKabaleRouteRoute: AdminKabaleRouteRouteWithChildren,
  AdminSystemRouteRoute: AdminSystemRouteRouteWithChildren,
  CitizenApplicationsRoute: CitizenApplicationsRoute,
  CitizenIndexRoute: CitizenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
