/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterProfileRouteImport } from './routes/register-profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as KabaleRouteRouteImport } from './routes/kabale/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KabaleIndexRouteImport } from './routes/kabale/index'
import { Route as CitizenIndexRouteImport } from './routes/citizen/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as KabaleDigitalIdsRouteImport } from './routes/kabale/digital-ids'
import { Route as KabaleApplicationsRouteImport } from './routes/kabale/applications'
import { Route as CitizenApplicationsRouteImport } from './routes/citizen/applications'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminKabalesIndexRouteImport } from './routes/admin/kabales/index'
import { Route as AdminDigitalIdsIndexRouteImport } from './routes/admin/digital-ids/index'
import { Route as AdminCitizensIndexRouteImport } from './routes/admin/citizens/index'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin/applications/index'
import { Route as AdminUsersCreateRouteImport } from './routes/admin/users/create'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId_'
import { Route as AdminKabalesCreateRouteImport } from './routes/admin/kabales/create'
import { Route as AdminKabalesKabaleIdRouteImport } from './routes/admin/kabales/$kabaleId_'
import { Route as AdminCitizensCitizenIdRouteImport } from './routes/admin/citizens/$citizenId'
import { Route as AdminUsersUserIdEditRouteImport } from './routes/admin/users/$userId.edit'
import { Route as AdminKabalesKabaleIdEditRouteImport } from './routes/admin/kabales/$kabaleId.edit'

const RegisterProfileRoute = RegisterProfileRouteImport.update({
  id: '/register-profile',
  path: '/register-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const KabaleRouteRoute = KabaleRouteRouteImport.update({
  id: '/kabale',
  path: '/kabale',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KabaleIndexRoute = KabaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KabaleRouteRoute,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/citizen/',
  path: '/citizen/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const KabaleDigitalIdsRoute = KabaleDigitalIdsRouteImport.update({
  id: '/digital-ids',
  path: '/digital-ids',
  getParentRoute: () => KabaleRouteRoute,
} as any)
const KabaleApplicationsRoute = KabaleApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => KabaleRouteRoute,
} as any)
const CitizenApplicationsRoute = CitizenApplicationsRouteImport.update({
  id: '/citizen/applications',
  path: '/citizen/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKabalesIndexRoute = AdminKabalesIndexRouteImport.update({
  id: '/kabales/',
  path: '/kabales/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDigitalIdsIndexRoute = AdminDigitalIdsIndexRouteImport.update({
  id: '/digital-ids/',
  path: '/digital-ids/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCitizensIndexRoute = AdminCitizensIndexRouteImport.update({
  id: '/citizens/',
  path: '/citizens/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersCreateRoute = AdminUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId_',
  path: '/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKabalesCreateRoute = AdminKabalesCreateRouteImport.update({
  id: '/kabales/create',
  path: '/kabales/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKabalesKabaleIdRoute = AdminKabalesKabaleIdRouteImport.update({
  id: '/kabales/$kabaleId_',
  path: '/kabales/$kabaleId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCitizensCitizenIdRoute = AdminCitizensCitizenIdRouteImport.update({
  id: '/citizens/$citizenId',
  path: '/citizens/$citizenId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdEditRoute = AdminUsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKabalesKabaleIdEditRoute =
  AdminKabalesKabaleIdEditRouteImport.update({
    id: '/kabales/$kabaleId/edit',
    path: '/kabales/$kabaleId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kabale': typeof KabaleRouteRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/register-profile': typeof RegisterProfileRoute
  '/citizen/applications': typeof CitizenApplicationsRoute
  '/kabale/applications': typeof KabaleApplicationsRoute
  '/kabale/digital-ids': typeof KabaleDigitalIdsRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen': typeof CitizenIndexRoute
  '/kabale/': typeof KabaleIndexRoute
  '/admin/citizens/$citizenId': typeof AdminCitizensCitizenIdRoute
  '/admin/kabales/$kabaleId': typeof AdminKabalesKabaleIdRoute
  '/admin/kabales/create': typeof AdminKabalesCreateRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/citizens': typeof AdminCitizensIndexRoute
  '/admin/digital-ids': typeof AdminDigitalIdsIndexRoute
  '/admin/kabales': typeof AdminKabalesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/kabales/$kabaleId/edit': typeof AdminKabalesKabaleIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/register-profile': typeof RegisterProfileRoute
  '/citizen/applications': typeof CitizenApplicationsRoute
  '/kabale/applications': typeof KabaleApplicationsRoute
  '/kabale/digital-ids': typeof KabaleDigitalIdsRoute
  '/admin': typeof AdminIndexRoute
  '/citizen': typeof CitizenIndexRoute
  '/kabale': typeof KabaleIndexRoute
  '/admin/citizens/$citizenId': typeof AdminCitizensCitizenIdRoute
  '/admin/kabales/$kabaleId': typeof AdminKabalesKabaleIdRoute
  '/admin/kabales/create': typeof AdminKabalesCreateRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/citizens': typeof AdminCitizensIndexRoute
  '/admin/digital-ids': typeof AdminDigitalIdsIndexRoute
  '/admin/kabales': typeof AdminKabalesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/kabales/$kabaleId/edit': typeof AdminKabalesKabaleIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kabale': typeof KabaleRouteRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/register-profile': typeof RegisterProfileRoute
  '/citizen/applications': typeof CitizenApplicationsRoute
  '/kabale/applications': typeof KabaleApplicationsRoute
  '/kabale/digital-ids': typeof KabaleDigitalIdsRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/kabale/': typeof KabaleIndexRoute
  '/admin/citizens/$citizenId': typeof AdminCitizensCitizenIdRoute
  '/admin/kabales/$kabaleId_': typeof AdminKabalesKabaleIdRoute
  '/admin/kabales/create': typeof AdminKabalesCreateRoute
  '/admin/users/$userId_': typeof AdminUsersUserIdRoute
  '/admin/users/create': typeof AdminUsersCreateRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/citizens/': typeof AdminCitizensIndexRoute
  '/admin/digital-ids/': typeof AdminDigitalIdsIndexRoute
  '/admin/kabales/': typeof AdminKabalesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/kabales/$kabaleId/edit': typeof AdminKabalesKabaleIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kabale'
    | '/forbidden'
    | '/login'
    | '/profile'
    | '/register'
    | '/register-profile'
    | '/citizen/applications'
    | '/kabale/applications'
    | '/kabale/digital-ids'
    | '/admin/'
    | '/citizen'
    | '/kabale/'
    | '/admin/citizens/$citizenId'
    | '/admin/kabales/$kabaleId'
    | '/admin/kabales/create'
    | '/admin/users/$userId'
    | '/admin/users/create'
    | '/admin/applications'
    | '/admin/citizens'
    | '/admin/digital-ids'
    | '/admin/kabales'
    | '/admin/users'
    | '/admin/kabales/$kabaleId/edit'
    | '/admin/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/profile'
    | '/register'
    | '/register-profile'
    | '/citizen/applications'
    | '/kabale/applications'
    | '/kabale/digital-ids'
    | '/admin'
    | '/citizen'
    | '/kabale'
    | '/admin/citizens/$citizenId'
    | '/admin/kabales/$kabaleId'
    | '/admin/kabales/create'
    | '/admin/users/$userId'
    | '/admin/users/create'
    | '/admin/applications'
    | '/admin/citizens'
    | '/admin/digital-ids'
    | '/admin/kabales'
    | '/admin/users'
    | '/admin/kabales/$kabaleId/edit'
    | '/admin/users/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kabale'
    | '/forbidden'
    | '/login'
    | '/profile'
    | '/register'
    | '/register-profile'
    | '/citizen/applications'
    | '/kabale/applications'
    | '/kabale/digital-ids'
    | '/admin/'
    | '/citizen/'
    | '/kabale/'
    | '/admin/citizens/$citizenId'
    | '/admin/kabales/$kabaleId_'
    | '/admin/kabales/create'
    | '/admin/users/$userId_'
    | '/admin/users/create'
    | '/admin/applications/'
    | '/admin/citizens/'
    | '/admin/digital-ids/'
    | '/admin/kabales/'
    | '/admin/users/'
    | '/admin/kabales/$kabaleId/edit'
    | '/admin/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  KabaleRouteRoute: typeof KabaleRouteRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RegisterProfileRoute: typeof RegisterProfileRoute
  CitizenApplicationsRoute: typeof CitizenApplicationsRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-profile': {
      id: '/register-profile'
      path: '/register-profile'
      fullPath: '/register-profile'
      preLoaderRoute: typeof RegisterProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kabale': {
      id: '/kabale'
      path: '/kabale'
      fullPath: '/kabale'
      preLoaderRoute: typeof KabaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kabale/': {
      id: '/kabale/'
      path: '/'
      fullPath: '/kabale/'
      preLoaderRoute: typeof KabaleIndexRouteImport
      parentRoute: typeof KabaleRouteRoute
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/kabale/digital-ids': {
      id: '/kabale/digital-ids'
      path: '/digital-ids'
      fullPath: '/kabale/digital-ids'
      preLoaderRoute: typeof KabaleDigitalIdsRouteImport
      parentRoute: typeof KabaleRouteRoute
    }
    '/kabale/applications': {
      id: '/kabale/applications'
      path: '/applications'
      fullPath: '/kabale/applications'
      preLoaderRoute: typeof KabaleApplicationsRouteImport
      parentRoute: typeof KabaleRouteRoute
    }
    '/citizen/applications': {
      id: '/citizen/applications'
      path: '/citizen/applications'
      fullPath: '/citizen/applications'
      preLoaderRoute: typeof CitizenApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kabales/': {
      id: '/admin/kabales/'
      path: '/kabales'
      fullPath: '/admin/kabales'
      preLoaderRoute: typeof AdminKabalesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/digital-ids/': {
      id: '/admin/digital-ids/'
      path: '/digital-ids'
      fullPath: '/admin/digital-ids'
      preLoaderRoute: typeof AdminDigitalIdsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/citizens/': {
      id: '/admin/citizens/'
      path: '/citizens'
      fullPath: '/admin/citizens'
      preLoaderRoute: typeof AdminCitizensIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/create': {
      id: '/admin/users/create'
      path: '/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AdminUsersCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId_': {
      id: '/admin/users/$userId_'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kabales/create': {
      id: '/admin/kabales/create'
      path: '/kabales/create'
      fullPath: '/admin/kabales/create'
      preLoaderRoute: typeof AdminKabalesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kabales/$kabaleId_': {
      id: '/admin/kabales/$kabaleId_'
      path: '/kabales/$kabaleId'
      fullPath: '/admin/kabales/$kabaleId'
      preLoaderRoute: typeof AdminKabalesKabaleIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/citizens/$citizenId': {
      id: '/admin/citizens/$citizenId'
      path: '/citizens/$citizenId'
      fullPath: '/admin/citizens/$citizenId'
      preLoaderRoute: typeof AdminCitizensCitizenIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId/edit': {
      id: '/admin/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AdminUsersUserIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kabales/$kabaleId/edit': {
      id: '/admin/kabales/$kabaleId/edit'
      path: '/kabales/$kabaleId/edit'
      fullPath: '/admin/kabales/$kabaleId/edit'
      preLoaderRoute: typeof AdminKabalesKabaleIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCitizensCitizenIdRoute: typeof AdminCitizensCitizenIdRoute
  AdminKabalesKabaleIdRoute: typeof AdminKabalesKabaleIdRoute
  AdminKabalesCreateRoute: typeof AdminKabalesCreateRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersCreateRoute: typeof AdminUsersCreateRoute
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
  AdminCitizensIndexRoute: typeof AdminCitizensIndexRoute
  AdminDigitalIdsIndexRoute: typeof AdminDigitalIdsIndexRoute
  AdminKabalesIndexRoute: typeof AdminKabalesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminKabalesKabaleIdEditRoute: typeof AdminKabalesKabaleIdEditRoute
  AdminUsersUserIdEditRoute: typeof AdminUsersUserIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCitizensCitizenIdRoute: AdminCitizensCitizenIdRoute,
  AdminKabalesKabaleIdRoute: AdminKabalesKabaleIdRoute,
  AdminKabalesCreateRoute: AdminKabalesCreateRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersCreateRoute: AdminUsersCreateRoute,
  AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
  AdminCitizensIndexRoute: AdminCitizensIndexRoute,
  AdminDigitalIdsIndexRoute: AdminDigitalIdsIndexRoute,
  AdminKabalesIndexRoute: AdminKabalesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminKabalesKabaleIdEditRoute: AdminKabalesKabaleIdEditRoute,
  AdminUsersUserIdEditRoute: AdminUsersUserIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface KabaleRouteRouteChildren {
  KabaleApplicationsRoute: typeof KabaleApplicationsRoute
  KabaleDigitalIdsRoute: typeof KabaleDigitalIdsRoute
  KabaleIndexRoute: typeof KabaleIndexRoute
}

const KabaleRouteRouteChildren: KabaleRouteRouteChildren = {
  KabaleApplicationsRoute: KabaleApplicationsRoute,
  KabaleDigitalIdsRoute: KabaleDigitalIdsRoute,
  KabaleIndexRoute: KabaleIndexRoute,
}

const KabaleRouteRouteWithChildren = KabaleRouteRoute._addFileChildren(
  KabaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  KabaleRouteRoute: KabaleRouteRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RegisterProfileRoute: RegisterProfileRoute,
  CitizenApplicationsRoute: CitizenApplicationsRoute,
  CitizenIndexRoute: CitizenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
